Make cxx dependency consistent
Without this, duplicated symbols error will occur when linking. e.g. ```/usr/bin/ld.gold: error: bazel-out/k8-fastbuild/bin/external/hats_crate_index__cxx-1.0.122/libcxx-1655806058.a(cxx-1655806058.cxx.65ec483138bb5bac-cgu.2.rcgu.o): multiple definition of 'cxxbridge1$string$reserve_total'
/usr/bin/ld.gold: bazel-out/k8-fastbuild/bin/external/using_cxx__cxx-1.0.122/libcxx-648010078.a(cxx-648010078.cxx.4f053d5d6e58c156-cgu.2.rcgu.o): previous definition here ``` We just need to pick one.

Change-Id: I51e335b758608335fdc20368141af3aa31e2974a