Declare projects in submodule as local repository so that bazel ignores them.
Right now `bazel build //...` fails if the submodules are fetched since it will
try to build kv-server and oak.
If you run bazel build //... you get the following if the submodules are pulled:
```
WARNING: Target pattern parsing failed.
ERROR: Skipping '//...': error loading package under directory '': error loading package 'submodules/oak/cc/containers/hello_world_trusted_app': cannot load '//bazel:defs.bzl': no such file
ERROR: error loading package under directory '': error loading package 'submodules/oak/cc/containers/hello_world_trusted_app': cannot load '//bazel:defs.bzl': no such file
INFO: Elapsed time: 0.477s
INFO: 0 processes.
ERROR: Build did NOT complete successfully
```

Unfortunately declare submodule as a local_repository didn't cause bazel to ignore them,
I had to declare each submodule.

Bug: b/344012112
Change-Id: I7127960f176afe4e3c039c0daf8d188a4385ee1c